# -*- coding: utf-8 -*-
"""Level1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9rc0auy3A51hBU9kcIl15jAhLACncnS

**Level 1: Basic
Build a basic “Hello World” agent
Develop a single agent (no tools) powered by an LLM**


**Sample interaction
User: What are the principles of OOPS?
AI: (whatever answer we get from LLM)**
"""

pip install agno

import os
from agno.agent import Agent
from agno.models.google.gemini import Gemini

os.environ["GOOGLE_API_KEY"] = "AIzaSyCB1q4oHOVdnVFoyAl4Y-HHQtiDA7I0GhM"

agent = Agent(name="HelloWorld", model=Gemini())
userInput=input("User: ")
response = agent.run(userInput)
print("AI Response:", response.content)